"""Generate the vendor support table spliced into README.md (#320).

WHY THIS IS GENERATED AND NOT TYPED
    Before this, nothing a user reads said which vendors Netwise actually
    works on. A hand-typed table would answer that once, on the day it was
    written, and then rot the first time a fixture changed or a new vendor
    was added -- the same failure this project has already found in every
    other hand-typed number (test counts, PR counts, a self-test's own
    baseline). So this is read from the fixtures and the real pipeline
    output, the same discipline tools/make_traceability.py already applies
    to a different document.

TWO CLAIMS, NOT ONE
    `tests/test_vendor_fixtures.py`'s own docstring is emphatic about this:
    "Batfish parsed it" is much weaker than "Netwise finds real problems in
    it". vendor-asa is the fixture where the two genuinely diverge -- it
    parses only PARTIALLY, and still produces a real finding, because #217
    taught analyse() to run the checks on a partly-read config rather than
    discard the analysis over a few unrecognised lines. Collapsing the two
    claims into one column would hide exactly the distinction this table
    exists to state.

WHY THIS SPLICES INTO README.md RATHER THAN OWNING A FILE OUTRIGHT
    The two existing generators in this repository (this one's siblings,
    make_traceability.py and make_phase3_backlog.py) each own a dedicated
    doc file and rewrite it whole. README.md is not a file anything should
    own outright -- it carries a great deal that has nothing to do with
    vendor support and is edited by hand for other reasons. So this
    generator owns only the block between two HTML comment markers,
    replacing exactly that slice and leaving everything else in the file
    untouched. If the markers are not present yet, it inserts the whole
    block once, at a fixed seam after the existing fixtures table in
    ## Usage.

HOW EACH VENDOR IS CLASSIFIED
    One call to analysis.pipeline.analyse() per fixture, reading its own
    return value rather than opening a second Batfish connection just to
    ask a question analyse() already answers internally:

      - a finding whose id ends in PARTIAL_PARSE_NUMBER -> parses partially
      - every finding sharing the pipeline's own fatal-parse summary
        (analyse() returns nothing else when parsing fails outright) ->
        does not parse
      - otherwise -> parses cleanly
      - any status="found" finding, independent of the above -> produces a
        finding

WHAT THIS DOES NOT PROVE
    That the fixture resembles a real customer's device of that vendor. It
    is a hand-written, deliberately faulted config -- see
    tests/test_vendor_fixtures.py's own module docstring for exactly what
    each one contains and why.

RUN
    python -m tools.make_vendor_support_table      (either form works)
    python tools/make_vendor_support_table.py
"""

from __future__ import annotations

import socket
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

REPO = Path(__file__).resolve().parent.parent
FIXTURES = REPO / "tests" / "fixtures"
README = REPO / "README.md"

#: Cosmetic labels only -- not a claim that can go stale, unlike the fixture
#: list itself, which is discovered from disk below rather than typed here.
DISPLAY_NAMES = {
    "vendor-arista": "Arista EOS",
    "vendor-asa": "Cisco ASA",
    "vendor-juniper": "Juniper",
    "vendor-nxos": "Cisco NX-OS",
}

MARKER_START = (
    "<!-- VENDOR-SUPPORT-TABLE:START -- generated by "
    "tools/make_vendor_support_table.py. Do not hand-edit; run the "
    "generator instead. -->"
)
MARKER_END = "<!-- VENDOR-SUPPORT-TABLE:END -->"

#: Where the runs the whole product otherwise checks with -- IOS. Not a
#: vendor fixture itself, just context the table states rather than implies.
BASELINE_VENDOR = "Cisco IOS"


def _vendor_fixtures() -> list:
    """Every vendor-* fixture on disk, sorted. One source of the vendor set
    -- the directory itself -- rather than a list typed here a second time."""
    if not FIXTURES.exists():
        return []
    return sorted(p.name for p in FIXTURES.iterdir()
                  if p.is_dir() and p.name.startswith("vendor-"))


def _batfish_is_up(host: str = "localhost", port: int = 9996,
                    timeout: float = 1.5) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def classify(vendor: str) -> "dict":
    """Run the real pipeline once and read both claims off its own output."""
    from analysis import pipeline

    results = pipeline.analyse(
        str(FIXTURES / vendor), snapshot_name=vendor.replace("-", "_"))

    fatal_summary = "Analysis could not run: the config did not fully parse"
    caveat_suffix = f"-{pipeline.PARTIAL_PARSE_NUMBER:03d}"

    produces_finding = any(f["status"] == "found" for f in results)
    is_fatal = bool(results) and all(
        f["summary"] == fatal_summary for f in results)
    is_partial = any(f.get("id", "").endswith(caveat_suffix) for f in results)

    if is_fatal:
        parses = "Does not parse"
    elif is_partial:
        parses = "Parses partially"
    else:
        parses = "Parses cleanly"

    return {
        "vendor": vendor,
        "display": DISPLAY_NAMES.get(vendor, vendor),
        "parses": parses,
        "produces_finding": produces_finding,
    }


def table_section() -> str:
    """The whole spliced block, markers included."""
    rows = [classify(v) for v in _vendor_fixtures()]

    lines = [MARKER_START, ""]
    add = lines.append

    add("### Vendor support")
    add("")
    add(
        f"Every check in Netwise runs against Batfish's own vendor-neutral "
        f"model, so nothing here is {BASELINE_VENDOR}-specific -- the "
        f"table below is about what Batfish itself can read from each "
        f"vendor's syntax, measured on real hand-written configs rather "
        f"than assumed."
    )
    add("")
    add(
        "**Parsing and finding something are different claims, and the "
        "table keeps them separate on purpose** -- "
        "`tests/test_vendor_fixtures.py` is the test suite that holds this "
        "apart. A config can parse cleanly and reveal nothing wrong; a "
        "config Batfish only partly understands can still produce a real, "
        "reliable finding about the part it did read. Neither implies the "
        "other."
    )
    add("")
    add("| Vendor | Parses | Produces a finding |")
    add("|---|---|---|")
    for row in rows:
        finding_text = "Yes" if row["produces_finding"] else "No"
        add(f"| {row['display']} | {row['parses']} | {finding_text} |")
    add("")
    add(
        "A config that does not parse at all is not listed as a supported "
        "vendor -- Batfish parses all four vendors measured here, three "
        "cleanly and one partially. \"Parses partially\" means Netwise "
        "still runs the checks and still attaches a loud caveat naming "
        "what it could not read (#217), rather than discarding the whole "
        "analysis over a few unrecognised lines."
    )
    add("")
    add(
        "Fixtures live under `tests/fixtures/vendor-*`, each carrying one "
        "deliberate, documented fault a policy-free analysis must catch. "
        "See that test file's own module docstring for what each fault is "
        "and why policy-free analyses are the ones that can see it."
    )
    add("")
    add(MARKER_END)
    return "\n".join(lines) + "\n"


def splice_into_readme(section: str) -> str:
    """Replace the marked block in README.md, or insert it once if absent."""
    text = README.read_text(encoding="utf-8")

    if MARKER_START in text and MARKER_END in text:
        start = text.index(MARKER_START)
        end = text.index(MARKER_END) + len(MARKER_END)
        return text[:start] + section.rstrip("\n") + text[end:]

    seam = "All live under `tests/fixtures/`.\n"
    if seam not in text:
        raise RuntimeError(
            "Could not find the fixtures-table seam in README.md to insert "
            "the vendor support table after. The markers are also absent, "
            "so this cannot self-heal -- insert "
            f"{MARKER_START!r} .. {MARKER_END!r} by hand once, near the "
            "existing fixtures table in ## Usage, then re-run this."
        )
    return text.replace(seam, seam + "\n" + section, 1)


def main() -> int:
    if not _batfish_is_up():
        print(
            "Batfish is not reachable on localhost:9996. This table is "
            "built from real analyse() output for four vendor fixtures, "
            "which needs Batfish running -- start it and try again."
        )
        return 2

    README.write_text(
        splice_into_readme(table_section()), encoding="utf-8", newline="\n"
    )
    print(f"wrote the vendor support table into {README.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
